# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup

title:            The Codeless Text
description:      Musings On the Writing of Code...
url:              https://amar-laksh.github.io


disqus:
      shortname: amar-laksh
author:
  name:           'Amar Lakshya'
  url:            https://github.com/amar-laksh

paginate:         2
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
sidebar_home_link:  true
sidebar_resume_link: /resume.pdf
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
github:
  repo:             https://github.com/amar-laksh/amar-laksh.github.io
